name: API Test
"on":
  push:
    branches:
      - master
env:
  CI: false
  REACT_APP_INSTAGRAM_API_KEY: ${{ secrets.REACT_APP_INSTAGRAM_API_KEY }}
  REACT_APP_SPOTIFY_CLIENT_ID: ${{ secrets.REACT_APP_SPOTIFY_CLIENT_ID }}
  REACT_APP_SPOTIFY_CLIENT_SECRET: ${{ secrets.REACT_APP_SPOTIFY_CLIENT_SECRET }}
